### ISSUE TITLE
[Issue]: flang-new: OpenMP declare target arrays crash

### ISSUE THREAD

**Issue by VeeEM** [ROCm/llvm-project#241]
### Problem Description

I'm seeing unexpected crashes with OpenMP offload code that uses declare target arrays after commit 13b4a9dcf329.

### Operating System

SUSE Linux Enterprise Server 15 SP5 (Cray OS on LUMI)

### CPU

AMD EPYC 7742 64-Core

### GPU

AMD Instinct MI250X

### ROCm Version

ROCm 6.2.2

### ROCm Component

flang

### Steps to Reproduce

I think the program below might reproduce the issue. The program should print "acc 500" but after 13b4a9dcf329 it prints:
```
Queue error - HSA_STATUS_ERROR_MEMORY_FAULT
Display only launched kernel:
Kernel 'omp target in _QQmain @ 11 (__omp_offloading_54bbb604_a0017379__QQmain_l11)'
OFFLOAD ERROR: Memory access fault by GPU 4 (agent 0x35ff90) at virtual address (nil). Reasons: Unknown (0)
Device pointer (nil) does not point into any (current or prior) host-issued allocation (might be a global, stack, or shared location).
```
Compiler flags: `flang-new -fopenmp -fopenmp-targets=amdgcn-amd-amdhsa --offload-arch=gfx90a`
```
program repr1
  integer, dimension(:), allocatable :: xs
  integer :: i, acc
  !$omp declare target (xs)

  allocate(xs(500))
  !$omp target enter data map(alloc:xs)
  xs = 1
  acc = 0
  !$omp target update to(xs)

  !$omp target map(acc)
  do i=1, 500
    acc = acc + xs(i)
  end do
  !$omp end target 
  
  print *, "acc", acc
end program
```

**Comment by ppanchad-amd** [comment]
Hi @VeeEM. Internal ticket has been created to investigate your issue. Thanks!

**Comment by tcgu-amd** [comment]
Hi @VeeEM, thanks for reaching out! Just to clarify, did the program work before https://github.com/ROCm/llvm-project/commit/13b4a9dcf329cca20d1870d5b0c74fb8e6c0c4e8?

**Comment by VeeEM** [comment]
Yes, the program works before 13b4a9dcf329.

**Comment by tcgu-amd** [comment]
Hi @VeeEM, I would like to add a quick update. After some investigation, it seems like prior to https://github.com/ROCm/llvm-project/commit/13b4a9dcf329cca20d1870d5b0c74fb8e6c0c4e8, the code was actually silently ignoring `!$omp declare target (xs)`. We are currently still in the progress of fixing declare target support. A temporary workaround is to remove the declare target line from the code. Thanks!

**Comment by lamb-j** [comment]
@tcgu-amd I'm guessing you mean amd-staging @ https://github.com/ROCm/llvm-project/commit/9529223204f4f3a7cf667d56f677694a5bde31d4? Not cherry-picking that specific commit

**Comment by tcgu-amd** [comment]
> [@tcgu-amd](https://github.com/tcgu-amd) I'm guessing you mean amd-staging @ [9529223](https://github.com/ROCm/llvm-project/commit/9529223204f4f3a7cf667d56f677694a5bde31d4)? Not cherry-picking that specific commit

Yes, thanks for the clarification!

**Comment by VeeEM** [comment]
I tested and that program does still crash at 9529223. I had to add -mcode-object-version=5 to get it to compile.

Another case I found that is crashing now and previously (before 13b4a9d) did not, is if an allocatable array member of a derived type variable is first allocated with enter data and then again with a map clause on a target directive like this:
```
program ta
implicit none

type dt
integer, dimension(:), allocatable :: xs
end type

type(dt) :: d
integer :: i

allocate(d%xs(10))
!$omp target enter data map(alloc: d%xs)

!$omp target map(alloc: d%xs)
do i=1, 10
  d%xs(i) = 1
end do
!$omp end target

!$omp target update from(d%xs)

print *, d%xs

end program
```
I'm not sure what the standard says but compiled with Cray Fortran 17.0.1 this program does print "10*1". This program can also be fixed to work with flang by removing the second map clause.

**Comment by tcgu-amd** [comment]
Hi @VeeEM, sorry for the delayed response; would you be able to verify if the code snippets above works on the [latest upstream build of the llvm-project](https://github.com/llvm/llvm-project)? Both appear to be running correctly now on our end. Thanks!

**Comment by VeeEM** [comment]
I checked and the snippets do work on upstream.

**Comment by tcgu-amd** [comment]
Hi @VeeEM, can you please verify if the issue is now fixed on amd-staging? Also, just a note, moving forward, changes for flang will no longer be tracked by amd-trunk-dev. All latest updates should be found on amd-staging. Thanks!

**Comment by VeeEM** [comment]
Still crashing with amd-staging at 21f46a5a8a2ca9d302213cd3171140085a896264.

Tested on a different machine now. This is an Ubuntu 24.04 machine with rocm 6.3 and a Radeon RX 7900 GRE GPU.

```
$ flang ta.f90 -fopenmp --offload-arch=gfx1100
$ ./a.out 
Display only launched kernel:
Kernel 'omp target in _QQmain @ 14 (__omp_offloading_805_3a6465__QQmain_l14)'
OFFLOAD ERROR: Memory access fault by GPU 1 (agent 0x63d59ef33e30) at virtual address 0x63d59ef4d000. Reasons: Page not present or supervisor privilege, Write access to a read-only page
Use 'OFFLOAD_TRACK_ALLOCATION_TRACES=true' to track device allocations
Aborted
```

```
$ flang repr1.f90 -fopenmp --offload-arch=gfx1100
$ ./a.out 
 acc 0
Display only launched kernel:
Kernel 'omp target in _QQmain @ 12 (__omp_offloading_805_3a6467__QQmain_l12)'
OFFLOAD ERROR: Memory access fault by GPU 1 (agent 0x624738168e30) at virtual address (nil). Reasons: Page not present or supervisor privilege
Use 'OFFLOAD_TRACK_ALLOCATION_TRACES=true' to track device allocations
Aborted
```
